spring.application.name=WorkForceMgmt

spring.datasource.url=jdbc:postgresql://localhost:5432/workforce-db
spring.datasource.username=postgres
spring.datasource.password=Xtreme@160r
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
# Define the path of the entry-point changelog
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml